### ISSUE TITLE
[testing] Create Smoke Test for APIs

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#10]
Once the basic setup is done we need to build set of test that ensure API end-points are tested against expected outputs.

**Comment by yspanchal** [comment]
List of API's URLs

(1) Get Trending
    http://www.newscout.in/api/v1/trending/?domain=newscout

(2) Bulk update categories
    http://www.newscout.in/api/v1/categories/bulk/

(3) List categories
    http://www.newscout.in/api/v1/categories/

(4) List liked news
    http://www.newscout.in/api/v1/articles/like-news-list/

(5) List bookmarked news
    http://www.newscout.in/api/v1/bookmark-articles/bookmark-news-list/

(6) Get list of Weekly and Monthly hashtags
    http://www.newscout.in/api/v1/tags/

(7) Save hashtag as passion
    http://www.newscout.in/api/v1/tags/save/

(8) List all sources
    http://www.newscout.in/api/v1/source/

(9) Bookmark article
    http://www.newscout.in/api/v1/articles/bookmark/

(10) Article Detail api
    http://www.newscout.in/api/v1/articles/2145/

(11) Article recommendation
    http://www.newscout.in/api/v1/articles/2145/recommendations/

(12) Signup api
    http://www.newscout.in/api/v1/signup/

(13) Login api
    http://www.newscout.in/api/v1/login/

(14) Logout api
    http://www.newscout.in/api/v1/logout/

(15) Forgot Password api
    http://www.newscout.in/api/v1/forgot-password/

(16) Change password api
    http://www.newscout.in/api/v1/change-password/

(17) Article Search api
    http://www.newscout.in/api/v1/article/search/?domain=newscout

(18) Menu list api
    http://www.newscout.in/api/v1/menus/

(20) Device add api
    http://www.newscout.in/api/v1/device/

(21) Social login api
    http://www.newscout.in/api/v1/social-login/

(22) Article create or update api
    http://www.newscout.in/api/v1/article/create-update/

(23) Get ad api
    http://www.newscout.in/api/v1/get-ads/

(24) Daily digest api
    http://www.newscout.in/api/v1/daily-digest/

(25) Campaign list api
    http://www.newscout.in/api/v1/campaign-categories/

(26) Campaign get, add and update api
    http://www.newscout.in/api/v1/campaign/

(27) Campaign delete api
    http://www.newscout.in/api/v1/campaign/(?P<cid>[-\d]+)/

(28) Group type list api
    http://www.newscout.in/api/v1/group-type/

(29) Adgroup get, add and update api
    http://www.newscout.in/api/v1/adgroup/

(30) AdGroup delete api
    http://www.newscout.in/api/v1/adgroup/(?P<cid>[-\d]+)/

(31) Advertisement get, add and update api
    http://www.newscout.in/api/v1/advertisement/

(32) Advertisement delete api
    http://www.newscout.in/api/v1/advertisement/(?P<cid>[-\d]+)/

**Comment by sidharthshah** [comment]
@Shivani-Padhye please look at [RequestClient](https://www.django-rest-framework.org/api-guide/testing/#requestsclient) from DRF this might help us figuring out API end points.
