### ISSUE TITLE
[enhancement] Tagging Interface

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#149]
We use to have a `/qc` section, can we refactor the code or integrate it into dashboard to make sure we've able to correct categories of pages.

**Comment by yspanchal** [comment]
QC Tool Integrated. https://github.com/fafadiatech/newscout_web/pull/292

URL:
http://www.newscout.in/dashboard/qc/

**Comment by Shivani-Padhye** [comment]
testing completed
