### ISSUE TITLE
[bug] More News section is Blank

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#151]
For some reason [this article](http://newscout.in/news/article/coronavirus-infection-found-after-cruise-ship-westerdam-passengers-disembark-in-cambodia-1451648/) More News section is not loading

**Comment by yspanchal** [comment]
@sidharthshah more news section for this article is not blank. Please check screenshot attached.
![Screenshot from 2020-02-19 14-51-11](https://user-images.githubusercontent.com/1426197/74820134-7cbfdc80-5327-11ea-8298-253f253012af.png)
