### ISSUE TITLE
[bug] Dashboard not rendering

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#159]
I've opened Dashboard as admin, I am not seeing any charts or numbers. Only blanks numbers are appearing. Please investigate this.

![Screenshot 2020-02-17 at 11 07 06 AM](https://user-images.githubusercontent.com/588467/74626463-b81aa980-5175-11ea-938d-70fc8486a924.png)

**Comment by yspanchal** [comment]
@sidharthshah please check one more time, all charts are rendered properly and i can see all counts. Please check screenshot attached.
![Screenshot from 2020-02-17 18-00-46](https://user-images.githubusercontent.com/1426197/74654176-be2d7c00-51af-11ea-8a0a-075a67086198.png)

**Comment by yspanchal** [comment]
@sidharthshah can i close this issue ?

**Comment by sidharthshah** [comment]
@yspanchal, there still seems to be issue with Dashboard render. I am attaching a secreenshot. Please investigate

<img width="1440" alt="Screenshot 2020-02-20 at 11 13 47 AM" src="https://user-images.githubusercontent.com/588467/74904615-35daf100-53d2-11ea-9cb7-a10ab0f31f95.png">
