### ISSUE TITLE
[enhancement] Integrate Ad-delivery in Frontend

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#161]
We've implemented Ads on Mobile App, please talk to `Gaurav` and see how we can integrate Ads onto frontend.

**Comment by hkacha** [comment]
@sidharthshah @yspanchal  I've integrated ad-delivery and deployed on server but I think there is some API related issue. So, I've not moved to done this card.

**Comment by yspanchal** [comment]
@hkacha Issue fixed. It was MEDIA_URL and MEDIA_ROOT issue.
