### ISSUE TITLE
[bug] Match order of Menu-Sub menu with Mobile Application

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#173]
We have a certain structure on `Mobile App` E.g. in `Sector Updates` we have `Banking` as first option. It would be a good idea to follow the same order

**Comment by sidharthshah** [comment]
If I load [this page](http://newscout.in/news/sector-updates/) it shows sections changing rapidly before settling with the order right

**Comment by Shivani-Padhye** [comment]
note that in the mobile app uncategorized section is named as **daily digest** and in a web application, it is included in the Misc category.
