### ISSUE TITLE
[enhancement] Allow users to read comments without logging in

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#182]
For this we might need to make few API changes.

**Comment by yspanchal** [comment]
https://github.com/fafadiatech/newscout_web/pull/189

**Comment by sidharthshah** [comment]
I've commented on [this article](http://newscout.in/news/article/coronavirus-hits-chinas-gold-jewellery-demand-as-shoppers-stay-away-1442517/), please figure out what the issue.
