### ISSUE TITLE
[enhancement] Multiple Subscriptions

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#192]
This has to be implemented in multiple ways. Lets look at following use-cases and figure out whats the best way to implement

1. A site has a premium "Members" section
1. A site can have different levels of "Subscriptions"

**Comment by jitendravarma** [comment]
There will be a base subscription model with multiple subscription role
1. Basic
2. Silver
3. Gold

Gold users can view and see everything unlimited articels per day
Silver user can view everything but limited articles per day
Basic users can just view the blurb, not the full article, no link to the article

Later there will be a payment gateway integration

**Comment by jitendravarma** [comment]
To edit subscription for end user
1. Login as admin
1. Go to subscription
1. Edit subscription for a given user
1. Change it to monthly or yearly

1. Loggin as the modified user
1. And check for media urls, and blurb content. Links wont be accessible to basic user but only for subscribed user
