### ISSUE TITLE
[enhancement] Implement Keyboard Shortcuts

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#197]
Implementing keyboard shortcuts would be cool. E.g. `[` for previous news `]` for next news. We can figure out the mapping -- but seems like something I want intuitively

**Comment by sidharthshah** [comment]
For now lets implement three shortcuts:

1. If on Article Details Page and someone types "->" key go to next article from that same category
2. If on Article Details Page and someone types "<-" key go to previous article from that same category 
3. If someone type "?" it should go to search bar to allow users to search

**Comment by hkacha** [comment]
@sidharthshah @Shivani-Padhye I've implemented keyboard shortcuts except "3. If someone type "?" it should go to search bar to allow users to search". For this issue I've created new issue.
