### ISSUE TITLE
[bug] Dashboard Issue for Safari

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#204]
Similar to like we're facing issue in Chrome, the Dashboard fails to load on Safari. I've checked this issue on `Version 13.0.5 (15608.5.11)`. Please investigate.

**Comment by yspanchal** [comment]
This bug is only related to safari, it is working on chrome on all systems, @Shivani-Padhye  has tested it.

**Comment by sidharthshah** [comment]
Duplicate of #159

**Comment by yspanchal** [comment]
Fixed in #280

Added Authorization header in get and post request.
Added auth token in cookies using res.set_cookies.
