### ISSUE TITLE
[bug] Authoring tool not working on Safari

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#205]
When I create an article for any category on `NewScout` it raises `Internal Server Error`. Please investigate.

**Comment by yspanchal** [comment]
This bug is only related to safari, it is working on chrome on all systems, @Shivani-Padhye  has tested it.

**Comment by yspanchal** [comment]
Fixed in https://github.com/fafadiatech/newscout_web/pull/280

* Added Authorization header in get and post request.
* Added auth token in cookies using res.set_cookies.

**Comment by Shivani-Padhye** [comment]
this issue is persisting while adding advertisements on safari.

**Comment by sidharthshah** [comment]
@hkacha I am not able to open Authoring tool on current site. Please investigate this issue. Its showing a blank screen as shown below

![Screenshot 2020-04-06 at 11 04 48 AM](https://user-images.githubusercontent.com/588467/78526043-782b8680-77f6-11ea-81b8-2c71e31a6f01.png)
