### ISSUE TITLE
[bug] content is unaligned

### ISSUE THREAD

**Issue by Shivani-Padhye** [fafadiatech/newscout_web#304]
there is a difference in our news content and source content. kindly check and compare.

Attaching images of content from source and newscout page.
1)source content page
 ![Screenshot from 2020-03-18 10-54-17](https://user-images.githubusercontent.com/57176686/76928974-00f68700-6909-11ea-8866-512572b9aede.png)

2)newscout content page
![Screenshot from 2020-03-18 10-53-49](https://user-images.githubusercontent.com/57176686/76929043-26839080-6909-11ea-82fb-1cf9a37ee36b.png)

**Comment by jitendravarma** [comment]
@hkacha Looks like issue at the crawler!

**Comment by hkacha** [comment]
Closing this issue because It's crawling related issue not an UI issue.
