### ISSUE TITLE
[testing] Automation Testing

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#324]
1. Create list of bugs that we can check for using Automated-Tests
2. Write Automated tests in `tests` folder {using `pytest`}
3. Break down tests into different bite-sized issues

**Comment by sidharthshah** [comment]
CC: @jitendravarma aka `Scrum Master`

**Comment by jitendravarma** [comment]
## 20 March 2020
1. Make sure you setup pytest with selenium on the new laptop by today
1. Write a sample 200 request test and make sure it works
1. Use test case wrapper from XC and make sure it works

**Comment by sidharthshah** [comment]
@Shivani-Padhye these are some test-cases we need to check that NewScout is working

1. Make sure login is working fine
2. Make sure trending section is working fine
3. Make sure search works {Check for results}
4. Make sure RSS page is rendering
5. Ensure Duplicates are not present on trending
6. Check Commenting workflow works
7. Ensure More News section is showing results

**Comment by sidharthshah** [comment]
@Shivani-Padhye I've reviewed and ran your test, only 2 of all the test are passing. I have attached error log for your reference. Kindly investigate

[error.log](https://github.com/fafadiatech/newscout_web/files/4461016/error.log)
