### ISSUE TITLE
[showstopper] Home Page is not Rendering

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#360]
Please look at attached screenshot, homepage is not rendering

![Screenshot 2020-03-29 at 8 16 40 AM](https://user-images.githubusercontent.com/588467/77838892-b8a35880-7195-11ea-94f9-193e0961c180.png)

**Comment by hkacha** [comment]
@sidharthshah Please check I've fixed and now it's working.
![newscout-homepage](https://user-images.githubusercontent.com/1704793/77839928-1e481280-719f-11ea-930f-b63e81ddaf4e.png)

**Comment by sidharthshah** [comment]
@sidharthshah yes its working fine. Thank you!
