### ISSUE TITLE
[enhancement] Show number of related stories in cluster 

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#369]
Would be nice to have N+ More Stories above Down Arrow. Please feel free to ping, me if you want to show me this requirement

**Comment by sidharthshah** [comment]
@rsqwerty please look at `+4` in screenshot below. What this tells is for a given section there are 5 stories. So apart from the one that is display there are 4 more stories.

Please let me know if you still have doubts

![Screenshot 2020-04-01 at 6 31 21 PM](https://user-images.githubusercontent.com/588467/78140128-21fdc280-7447-11ea-90a7-924cb1654981.png)

**Comment by Shivani-Padhye** [comment]
had discussion on this issue with rushikesh, he is working on it.
