### ISSUE TITLE
[enhancements] Search UI Enhancements

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#378]
1. Please show Total Number of Results
1. `Related Queries` need to be adjusted for Mobile Web
1. Dismiss Filter after user clicks anywhere outside
1. Adjust font size for Filters for Mobile Web
1. Give option to clear current selection in filters

**Comment by hkacha** [comment]
@sidharthshah @Shivani-Padhye I've implemented all changes except fetching "Related Queries". And I've created an issue for implement related queries.
