### ISSUE TITLE
[enhancements] Misc UI Changes

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#397]
Please look at following screenshots:

![screenshot-ui-1](https://user-images.githubusercontent.com/588467/78417258-00225c80-764e-11ea-8771-ec3870e14092.png)
![screenshot](https://user-images.githubusercontent.com/588467/78417262-04e71080-764e-11ea-9a5d-fadcfc33f570.png)

**Comment by sidharthshah** [comment]
Make section title clickable. E.g. Make "Tech" clickable as shown in screenshot below

![Screenshot 2020-04-04 at 10 34 47 AM](https://user-images.githubusercontent.com/588467/78419125-349f1400-7660-11ea-90df-b2729b9fcd35.png)

**Comment by Shivani-Padhye** [comment]
can not reproduce this issue.
