### ISSUE TITLE
[enhancement] Chart Related Changes

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#402]
1. Render charts in 2 Column Layout. The on Column should be a fall back for smaller devices {e.g. iPad}
1. Change `All Article Changes` chart to [Simple Line Chart](https://recharts.org/en-US/examples/SimpleLineChart)
1. By default show charts from last 30 days as opposed to 7 days
1. Make color scheme consistent for all charts. We should not use more than 2-3 different colors for charts.
1. Rationalise `Articles Per Author` and `Interactions Per Author`

**Comment by hkacha** [comment]
@sidharthshah I've implemented charts from last 30 days. As per 2 column layout data not display properly. I've attached some screenshots of please check and let me know which one is proper?
![7days-2clm](https://user-images.githubusercontent.com/1704793/78880398-f85e2000-7a72-11ea-818c-3bfbbf2d3be5.png)
![7days-full-width](https://user-images.githubusercontent.com/1704793/78880407-fd22d400-7a72-11ea-8a0a-b9e00b94b1cf.png)
![30days-2clm](https://user-images.githubusercontent.com/1704793/78880412-001dc480-7a73-11ea-8d63-c1bef2c69123.png)
![30days-full-width](https://user-images.githubusercontent.com/1704793/78880425-03b14b80-7a73-11ea-8be5-7c4b48d807d4.png)

**Comment by sidharthshah** [comment]
@hkacha I've look at the current layout here is what I suggest

1. Hide Side Bar by Default {Our charts look much better when the graphs are hidden}
1. The current first row seems fine so keep it as is
1. `Articles per Category` can be shifted above the current first row. This way the new Layout would be as follows {Row 1: Articles Per Category, Row 2: All Articles Open & Articles Per Platform, Row 3: Interactions Per Category, Row 4: Avg. Interactions per Session, Row 5: Articles Per Author & Interactions Per Author, Row 6: Avg. Articles Per Session}
