### ISSUE TITLE
[enhancement] While creating New Ad Group allow Selecting "All" cateogries

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#405]
Right now there is no option to save "All" categories we need to add this

![Screenshot 2020-04-06 at 10 51 09 AM](https://user-images.githubusercontent.com/588467/78525405-ae680680-77f4-11ea-8204-04bc0a1f2e2a.png)

**Comment by Shivani-Padhye** [comment]
I have selected "Select All" option and added the group. It is working properly.
