### ISSUE TITLE
[bug] Changes to Ads Form

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#407]
1. Change caption of first control to "Campaign" 
1. Change caption of second control to "Bid Type"
1. Change caption of "Form submitted successfully" to "Ad create successfully"

![Screenshot 2020-04-06 at 10 54 31 AM](https://user-images.githubusercontent.com/588467/78525522-0868cc00-77f5-11ea-8178-6de34b5c9751.png)

**Comment by Shivani-Padhye** [comment]
ad is not getting added. internal server error is occurring. so cannot test this.

**Comment by Shivani-Padhye** [comment]
This issue is partially working, and ad still not getting added. control names are changed.
