### ISSUE TITLE
[docs] Update documentation on frontend development

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#412]

**Comment by hkacha** [comment]
@sidharthshah @fafadiatech Please find below updated documentations of newscout webapp installation and newscout-react-component installation.
https://docs.google.com/document/d/1kV6bSgdceshnB9isvjQ1rgdET3RrWN4wXXBXDlWEt6c/edit?usp=sharing

**Comment by sidharthshah** [comment]
@hkacha this issue has been done from your end. I need to integrate this into our Official Documents.
