### ISSUE TITLE
[devops] Check status of crawler

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#416]
Crawler seems to be down, please investigate whats happening

**Comment by jitendravarma** [comment]
Well, when you encounter this again, check if the services are up and running
1. Check supervisor is running for all the programs
1. Check mongodb is running

There is an know supervisor issue, that it fails to kill programs upon restart.
So, I have edited the supervisord.conf to SIGKILL on restart, which fixed the supervisor issue.

Second, mongo db was not running on the prod server. I add it to systemctl and restarted it.

**Comment by Shivani-Padhye** [comment]
As discussed with @rsqwerty, it is working properly.
