### ISSUE TITLE
[enhancement] Change response of "comment-captcha/" API

### ISSUE THREAD

**Issue by gmcodebuster** [fafadiatech/newscout_web#422]
Remove double quotes from result value inside body object.

{
    "header": {
        "status": "1"
    },
    "body": {
        "result": "{\"status\": 1, \"new_captch_key\": \"a4be2cd778cad436136ac35ad332581ec3baf5de\", \"new_captch_image\": \"/captcha/image/a4be2cd778cad436136ac35ad332581ec3baf5de/\"}"
    }
}

**Comment by sidharthshah** [comment]
@gmcodebuster or @rsqwerty can you please confirm if this issue has been completed?

**Comment by rsqwerty** [comment]
Its completed sir.
