### ISSUE TITLE
[enhancement] Mail Admin of Site Report Daily/Weekly/Monthly

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#425]
We need to build out functionality to send update emails Specifically with regards to Analytics we're generating. This needs to be an email digest {something similar to what ERPNext is doing}

Lets discuss the requirements of this feature in more details

**Comment by sidharthshah** [comment]
@hkacha note the requirements for this task

## Daily Update Email

1. Sent everyday
2. Contains report in HTML form from Dashboard with 'Today Selected'
3. Attach Report as PDF
4. Have Key Metrics in Email

## Weekly Update Email

1. Sent on every Sunday
2. Contains report in HTML form from Dashboard with '7 Days Selected'
3. Attach Report as PDF
4. Have Key Metrics in Email

## Monthly Update Email

1. Sent on last day of Month E.g. 31st Jan/30th April etc.
2. Contains report in HTML form from Dashboard with '30 Days Selected'
3. Attach Report as PDF
4. Have Key Metrics in Email

**Comment by hkacha** [comment]
Not an issue.
