### ISSUE TITLE
[bug] Captcha is not getting rendered

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#437]
For some reason the Captcha is not getting rendered. Please investigate

![Screenshot 2020-04-09 at 7 14 06 PM](https://user-images.githubusercontent.com/588467/78901744-67993b80-7a96-11ea-8e13-c5d0e0dc97d3.png)

**Comment by sidharthshah** [comment]
@rsamantra, can you please comment on what the issue was?

**Comment by Shivani-Padhye** [comment]
after refreshing the page I was not able to reproduce this issue. kindly test it on your device, so that I can close and comment. @sidharthshah.

**Comment by sidharthshah** [comment]
@rsamantra and @Shivani-Padhye this is happening on Mac. Will show it to you folks today.
