### ISSUE TITLE
[chore] List of APIs for Testing

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#443]
Can you please create list of API {or point me to some Documentation in case we already have} it. I would want to write some sort of test suite for API - which will allow us to do CI/CD.

**Comment by rsqwerty** [comment]
List of APIs :-
"/api/v1/trending/"
"/api/v1/categories/bulk/"
"/api/v1/categories/"
"/api/v1/articles/like-news-list/"
"/api/v1/bookmark-articles/bookmark-news-list/"
"/api/v1/tags/save/"
"/api/v1/source/"
"/api/v1/articles/bookmark/"
"/api/v1/articles/article_id/
"/api/v1/login/"
"/api/v1/logout/"
"/api/v1/signup/"
"/api/v1/forgot-password/"
"/api/v1/change-password/"
"/api/v1/device/"
"/api/v1/article/search/?domain=newscout"
"/api/v1/menus/?domain=newscout"
"/api/v1/article/create-update/"
"/api/v1/article/status/"
"/api/v1/article/create-update/"
"/api/v1/daily-digest/?device_id=device_id"
"/api/v1/articles/article_id/recommendations/"
"/api/v1/comment/?article_id=article_id"
"/api/v1/comment/"
"/api/v1/article-like/"
"/analytics/all-articles-open/"
"/analytics/articles-per-platform/"
"/analytics/articles-per-category/"
"/analytics/interactions-per-category/"
"/analytics/articles-per-author/"
"/analytics/interactions-per-author/"
"/analytics/aticles-per-session/"
"/analytics/interactions-per-session/"
