### ISSUE TITLE
[enhancement] Show empty state for Bookmarks

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#446]
[Look at the first image slide here](https://uigarage.net/videos-on-ios-by-instapaper/) we need to show something similar for `My Bookmarks`. When there are no bookmarks we should show a graphic and below it say "Bookmarks allow you keep track of stories you'd like to remember. Start Bookmarking now"

Right now its showing blank screen.

![Screenshot 2020-04-11 at 9 29 02 AM](https://user-images.githubusercontent.com/588467/79034990-a8e53480-7bd7-11ea-99d6-7fa5bcb5cc3c.png)

**Comment by Shivani-Padhye** [comment]
This issue not solved yet. i am still getting this issue. please check in other devices.

**Comment by hkacha** [comment]
I've attached screenshot of empty bookmark page.
![blank-bookmark](https://user-images.githubusercontent.com/1704793/79307018-d867aa00-7f13-11ea-880b-e981cf937647.png)

**Comment by hkacha** [comment]
@Shivani-Padhye I've fixed issue. Please check and let me know.
