### ISSUE TITLE
[chore] Standardize vscode and pre-commit workflow setup

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#46]
We've got some good documentation on

1. [VSCode Setup for Python](https://www.fafadiatech.com/resources/technical/python/vs_code_setup.html)
1. [Pre-commit workflow setup for Python](https://www.fafadiatech.com/resources/technical/python/precommit_workflow.html)

We need to integrate them on NewScout. CC: @yspanchal

**Comment by yspanchal** [comment]
Issue Completed. PR: https://github.com/fafadiatech/newscout_web/pull/62
