### ISSUE TITLE
[enhancement] Ensure icons adjust to larger screen

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#481]
Notice how our side-menu is looking on larger screen. Can we do anything to make icons sharpers on large screen.

![Screenshot 2020-04-18 at 8 34 03 PM](https://user-images.githubusercontent.com/588467/79641269-0d922780-81b4-11ea-90b5-a0551cab0f02.png)

**Comment by hkacha** [comment]
Fixed issue.
