### ISSUE TITLE
[bug] icons and subcategory names are not visible.

### ISSUE THREAD

**Issue by Shivani-Padhye** [fafadiatech/newscout_web#523]
as user can see the names of subcategories are repeated and icons are also not visble , throwing 404 not found error. attaching the ss for reference.
![Screenshot from 2020-04-30 10-54-40](https://user-images.githubusercontent.com/57176686/80675534-50b49a80-8ad2-11ea-839d-524d9cfa90b9.png)

**Comment by hkacha** [comment]
Closing this duplicate issue.
