### ISSUE TITLE
[enhancement] Replace all icons with font-awesome 

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#558]
Right now we're using image icons, see if we can replace those by using font-awesome. This will allow us to scale and take advantage of vector

**Comment by JoseChavez98** [comment]
Hi! I'll love to collaborate on the issue. Can you assign me?

**Comment by sidharthshah** [comment]
Hi @JoseChavez98, this one is already assigned. There are bunch of other tasks you can take on. What would be a good way to connect with you? I'd like to talk to you and figure out how we can collaborate. 👍

**Comment by JoseChavez98** [comment]
Sure thing! @sidharthshah  This is my email ginger.melo.jc@gmail.com .
Feel free to contact me

**Comment by hkacha** [comment]
Fixed issue.
